### ISSUE TITLE
Button to Add Player and Add Monster is covered by the keyboard

### ISSUE THREAD

**Issue by LoganRoyer** [ConnorMcLean1/5E-Initiative-Tracker#94]
Currently if you click on the button to add a player or monster and the keyboard appears as you input data into the fields, the keyboard blocks the button to add another player. This can get annoying as the user to constantly have to minimize the keyboard when adding a new player.

**Comment by patrick-springford** [comment]
Made the keyboard hide on enter click in Combatant Activity and on relevant button presses in Combat Activity.
